#!/bin/sh

ln -s `pwd`/vimrc ~/.vimrc
ln -s `pwd`/pryrc ~/.pryrc
ln -s `pwd`/zshrc ~/.zshrc
ln -s `pwd`/bashrc ~/.bashrc
ln -s `pwd`/shellrc ~/.shellrc
ln -s `pwd`/aliasesrc ~/.aliasesrc
ln -s `pwd`/tmux.conf ~/.tmux.conf
